### ISSUE TITLE
unixform true when saving eml

### ISSUE THREAD

**Issue by dani0805** [coddingtonbear/django-mailbox#100]
Dear all, 

is there any reason for 
`ContentFile(message.as_string(unixfrom=True))`
in models.py line 335?

this is breaking the mail format when we use the stored eml by inserting the From nobody <date> separator in the file.
We need to purge this before using it to set the raw body of a new message. Using 
`ContentFile(message.as_string())`
would avoid this
<img width="1196" alt="screen shot 2016-05-27 at 16 40 09" src="https://cloud.githubusercontent.com/assets/8342299/15611407/81a8004a-242a-11e6-87c6-8abff6f0305a.png">

**Comment by ad-m** [comment]
I don't see any reason.

**Comment by dani0805** [comment]
Should I post a pull request?

**Comment by coddingtonbear** [comment]
Agreed; I think `unixfrom` is neither necessary nor helpful; I'll fix it in just a few minutes.

**Comment by coddingtonbear** [comment]
Fixed in v4.5.3;  thanks for the report @dani0805!
