### ISSUE TITLE
command SEARCH illegal in state AUTH, only allowed in states SELECTED

### ISSUE THREAD

**Issue by pushpan** [coddingtonbear/django-mailbox#101]
occurred when fetching mails from imap.163.com:  (imap.py)
error at /admin/django_mailbox/mailbox/
command SEARCH illegal in state AUTH, only allowed in states SELECTED

```
def _get_all_message_ids(self):
    # Fetch all the message uids
    response, message_ids = self.server.uid('search', None, 'ALL') ...
    message_id_string = message_ids[0].strip()
    # Usually `message_id_string` will be a list of space-separated
    # ids; we must make sure that it isn't an empty string before
    # splitting into individual UIDs.
    if message_id_string:
        return message_id_string.decode().split(' ')
```

**Comment by coddingtonbear** [comment]
At a glance, that sounds like you may not have entered the right password; have you double checked?

**Comment by spatialbits** [comment]
Hi there, I am getting this error as well for an imap mailbox. The exception occurs if I specify a folder on the end of the url; it works fine without the folder parameter. 
bombs: `imap://user:pass@mail.example.com?folder=django_folder`
works fine: `imap://user:pass@mail.example.com`

**Comment by spatialbits** [comment]
It was just a bad foldername. For my imap server I needed to preface the folder name with `INBOX.`; so the uri is now:
`imap://user:pass@mail.example.com?folder=INBOX.django_folder`

**Comment by flooreeda** [comment]
Prefixing my folder value with INBOX.* worked for me as well. Thanks @spatialbits!

**Comment by pfouque** [comment]
Looks solved!
PS: Feel free to open a pull request to improve the documentation, as you had like to find
