### ISSUE TITLE
Trigger Event when receiving new email

### ISSUE THREAD

**Issue by lonewolf911** [coddingtonbear/django-mailbox#110]
@coddingtonbear 
@ad-m 

I try to using signal to trigger an event whenever receiving new email in my mailbox but I do not know exactly how to. I did like some example i found out on Internet. 

The handler did not run when I have new email, it just run after I call `get_new_mail()`. Please tell me what I'm doing wrong here.

*products/signals/handlers.py*
```
from django_mailbox.signals import message_received
from django.dispatch import receiver


@receiver(message_received)
def mail_update(sender, message, **kwargs):
    print(message)
```

*products/apps.py*
```
from django.apps import AppConfig


class MailConfig(AppConfig):
    name = 'products'

    def ready(self):
        import products.signals.handlers
```

*products/__init__.py*
```
default_app_config = 'products.apps.MailConfig'
```

**Comment by coddingtonbear** [comment]
I'm not quite sure I follow -- what do you mean by "did not run when I have new email"?  We emit that signal whenever a new message is processed, and that is generally just when you run `get_new_mail`, but also might be when a new message is entered into Django-Mailbox via another method.  Care to clarify?

**Comment by ad-m** [comment]
The signals was executed for every message downloaded. Downloading have to be started. There is a way to start pooling (periodically downloading). See http://django-mailbox.readthedocs.io/en/stable/topics/polling.html and https://en.wikipedia.org/wiki/Polling_(computer_science).

I use signals and ```python manage.py getmail``` in cron in production use. You have too use signals and any a way of starting pooling to receive emails.

**Comment by lonewolf911** [comment]
Thank for the quick reply.
Oh, I see. So I have to call `get_new_mail()` to init the signal, my bad.
What I want here is  how to check my mailbox 24/7, not only when I call `get_new_mail()`. Any ideas or instruction to help me out here ?

Once again, thank you very much.

**Comment by ad-m** [comment]
@lonewolf911 , there is a several ways to init the signal. There is all listed at http://django-mailbox.readthedocs.io/en/stable/topics/polling.html mentioned in my previous comment. I suggest use ```python manage.py getmail``` in cron eg. every 5 minutes.

**Comment by lonewolf911** [comment]
Thank you very much for helping me out here. I already look into cron :+1:

**Comment by ad-m** [comment]
@coddingtonbear , do you can close this issue?
