### ISSUE TITLE
Register of last success pooling

### ISSUE THREAD

**Issue by ad-m** [coddingtonbear/django-mailbox#111]
Hello @coddingtonbear ,

I often have issues related to processing incoming mail. Some in django-mailbox mail processing, some in custom signals code. In last time unable to load mysqldb (weird issue not fail running gunicorn fail, only cron job), so processing fail silently too. In most cases I receive sentry notification, but in last time I miss one, so mail processing fail by two days. 

I would like add monitoring of processing incoming mail by Zabbix to detect delay in mail processing.

What do you think about add field `last_pooling` to `django_mailbox.models.Mailbox` which will store date and will be updated **after** successful `Mailbox.get_new_mail` execution? I believe that the changes in the data model should be discussed.

Greetings,

**Comment by ad-m** [comment]
I would like mark that diff to signals ```message_received``` or max of ```Message.processed```. Signals ```message_received``` was executed only when messages was downloaded. If there is no new messages then signals wasn't fired and max of ```Message.processed``` wasn't changed.

**Comment by coddingtonbear** [comment]
Yep, that sounds good to me, actually, as long as you name the field `last_polling` ;-).

On that note, how would you feel about being a maintainer?  I haven't had enough time available to be a very good sole maintainer and could totally use the help.  If you agree, I'll give you direct access to the repo, but in exchange you agree to:

1. Post PRs for review for any major changes.
2. Try not to break the existing tests, and try to write tests for any new changes.
3. Continue being as helpful to all of the other contributors as you already are.

Let me know if you're willing!

**Comment by ad-m** [comment]
@coddingtonbear , this sound nice. I accept all your requirements. :ok_hand:

Do you think you able to give me direct access to the repo without creating the organization?

**Comment by coddingtonbear** [comment]
Yep!  You should have an invite in your inbox right now.

**Comment by ad-m** [comment]
@coddingtonbear , I see. Everything seems to work. So lets start work on ```last_polling```! :+1:

**Comment by pfouque** [comment]
Solved by #112
