### ISSUE TITLE
Body of a long email is empty

### ISSUE THREAD

**Issue by lonewolf911** [coddingtonbear/django-mailbox#116]
I'm sorry if I'm troubling you but I don't know where else to ask. Here are my problem.

In my local, everything is working fine. But on my deployment, I don't know why, when I'm trying to receive a long email, the body of that email is empty in django_mailbox_message, it still working with short email

![2016-08-22 13_18_22-mysql workbench](https://cloud.githubusercontent.com/assets/7744571/17845498/7adc0834-686c-11e6-984b-24d858b05b72.png)

**Comment by ad-m** [comment]
Here is it ok to ask.

Do you can provide anonymized (replaced sensitive data with XXXX) *.eml files of broken parsed message? See #107 how to debug this kind of issues.

**Comment by lonewolf911** [comment]
Thank you for quick reply.
This is not a attachment, just a simple text msg. With just 150 lines of simple text like this, the body of email become empty
> This is a test email

`test mail 16` is a short mail and `test mail 17` is a long one with empty body

It's still working on my local, just a problem with deployment server. I will try to follow #107 and debug, will update asap

**Comment by ad-m** [comment]
All email messages can be converted to ```*.eml``` file. It doesn't matter there is attachment or not. ```*.eml``` is filetype for storing each email message. It contains information about header (subject, recipient, sender), body and attachments. Here is a examples of messages: https://github.com/coddingtonbear/django-mailbox/tree/master/django_mailbox/tests/messages

**Comment by lonewolf911** [comment]
@ad-m 
It's ok now, I don't know why, maybe just my deployment or something else.

I modified directly to `models.py` like this:
```
    def get_new_mail(self, condition=None):
        """Connect to this transport and fetch new messages."""
        new_mail = []
        connection = self.get_connection()
        if not connection:
            return new_mail
        for message in connection.get_message(condition):
            logger.error("Message before processing:")
            logger.error(message.as_string())
            msg = self.process_incoming_message(message)
            logger.error("Message after processing:")
            logger.error(msg.get_email_object().as_string())
            new_mail.append(msg)
        return new_mail
```

And it running fine, then revert it back to the original, it still running fine. I'm not sure what's the problem but it's ok now. Thank you for your help :)

**Comment by ad-m** [comment]
Is it ready to close?
