### ISSUE TITLE
Docs: Upstreams docs (django) changed ..

### ISSUE THREAD

**Issue by guettli** [coddingtonbear/django-mailbox#118]
The upstream docs (django) changed.

Current docs from your app:

> As with all django signals, this should be loaded either in an app’s models.py or somewhere else loaded early on. If you do not load it early enough, the signal may be fired before your signal handler’s registration is processed

From http://django-mailbox.readthedocs.io/en/latest/topics/signal.html

The docs of django tell you something different today. Please update your (redundant) docs, or remove them and provide just a link. Sometimes less is more :-)

My background: A team mate was confused by your docs, since they tell something different ...

**Comment by ad-m** [comment]
Got catch. Docs for django 1.8 mention:
> Since ready() didn’t exist in previous versions of Django, signal registration usually happened in the models module.
I will review impact of that on django-mailbox in the weeks and prepare pull requests of update docs. If you like, you can prepare pull requests too, because I have problems with the English language.

**Comment by guettli** [comment]
I think the best solution is to provide a link to the upstream docs and not more.This is free of redundancy and thus won't get outdated.

**Comment by coddingtonbear** [comment]
@guettli -- could you file a pull request updating the docs to include that update?

**Comment by pfouque** [comment]
It seems fixed since!
