### ISSUE TITLE
Reason for MessageAttachment

### ISSUE THREAD

**Issue by guettli** [coddingtonbear/django-mailbox#119]
I could not find it in the docs: 

 Why does MessageAttachment exist?

What is the benefit?

Why not store the mail in one BLOB/CharField?

**Comment by ad-m** [comment]
Storing binary files (sometimes big eg. 25MB+ PDF) as blob/charfield is a bad idea. DBMS are not designed to store files. It is widely discussed in the literature of the subject (see https://programmers.stackexchange.com/questions/150669/is-it-a-bad-practice-to-store-large-files-10-mb-in-a-database , .

MessageAttachment is used to reference files on filesystem rather store them in database (see https://django-mailbox.readthedocs.io/en/latest/topics/appendix/message-storage.html ).

**Comment by guettli** [comment]
Thank you very much for your fast reply. 

BTW, the literature or SQL databases is often more than twenty years old. Today, in year 2016, the hardware for servers is quite different.

**Comment by ad-m** [comment]
It is good to mention that django ORM SELECT all fields by default which will have on django memory usage impact too. If some data was downloaded from database then it was put in python object, so increase memory usage. You can use ```QuerySet.values()```, but makes it necessary to repeat the limiting fields, and in many cases, problems with compatibility of such a solution.

If you like display a few messages on single view using blob field and skip ```values()``` then you have very high memory usage per each message due a few object with a whole messages with eg. 25MB attachment each. Modern computers still do not have unlimited memory capacity.

**Comment by coddingtonbear** [comment]
@guettli -- incidentally, django-mailbox *used* to store the whole e-mail message in the database, but there were complaints because Django supports a whole slough of database backends and not all of them handle large blobs of data well.  Given that there aren't any guarantees that users aren't using either an extremely old version of MySQL or even just a local Sqlite3 database, we decided to store attachments as files.
