### ISSUE TITLE
Is it safe to delete files in the DJANGO_MAILBOX_ATTACHMENT_UPLOAD_TO directory?

### ISSUE THREAD

**Issue by ses4j** [coddingtonbear/django-mailbox#121]
My DJANGO_MAILBOX_ATTACHMENT_UPLOAD_TO folder `mailbox_attachments/%Y/%m/%d/` has gotten very large.  Is it safe to delete the files in it?  What happens if I try to read one of the messages whose attachments got purged?  Does it redownload them?  Crash?  Simply not show that attachment?  

I'd think it would be helpful for the documentation to address this.

**Comment by coddingtonbear** [comment]
I really wouldn't recommend deleting the files directly; it'll totally blow up!  If you do want to get rid of attachments, though, you can *definitely* delete the [MessageAttachment records](https://github.com/coddingtonbear/django-mailbox/blob/master/django_mailbox/models.py#L703) directly (by calling their `delete` method).  That'll both delete the files and our record of the attachment in [a way that is fully-handled](https://github.com/coddingtonbear/django-mailbox/blob/master/django_mailbox/models.py#L623).

**Comment by ses4j** [comment]
To be sure, an attachment file directory grows unbounded forever unless something is done, yes?  We tie the Message objects in the DB to something, so I don't want to purge the whole Message.  Is it safe to simply write a cron job to do this every night?  

```
from django.utils import timezone
from datetime import timedelta
from django_mailbox.models import MessageAttachment
MessageAttachment.objects.filter(message__processed__lt=timezone.now() - timedelta(days=30)).delete()
```

If so, it might be helpful to mention it in the doc if it's not already -- it's filled up our drives a few times.

**Comment by ses4j** [comment]
... I guess the code needs to be this:

```
for ma in MessageAttachment.objects.filter(message__processed__lt=timezone.now() - timedelta(days=30)):
    ma.delete()
````

?
