### ISSUE TITLE
mbox Mailboxes do not delete the consumed e-mails

### ISSUE THREAD

**Issue by adroffner** [coddingtonbear/django-mailbox#128]
* [Mailbox.flush()](https://docs.python.org/2/library/mailbox.html#mailbox.Mailbox.flush)
* [transports.generic.GenericFileMailbox.get_message()](https://github.com/coddingtonbear/django-mailbox/blob/master/django_mailbox/transports/generic.py)

I believe the **mbox** mail transport requires that its **flush()** method be called. Right now, I don't see my e-mails being deleted as they are read by the Django command **getmail**.

**Comment by ad-m** [comment]
@adroffner , you are right! Fixed!
