### ISSUE TITLE
Default models.MailAttachment.document filename is too short

### ISSUE THREAD

**Issue by adroffner** [coddingtonbear/django-mailbox#129]
The **MailAttachment.document** field is too short & raises the error below. The default **FileField(..., max_length=100)** does not hold long enough filenames.

Can **MailAttachment.document** accept a configured **max_length**, or have the default set higher?

ERROR: [django.security.SuspiciousFileOperation: 204] >> Storage can not find an available filename for ".../mailbox_server/media/mailbox_attachments/2017/02/16/f826fb7b4b1949fcaa9d4108a8b3af44_466Pkvz.rtf". Please make sure that the corresponding file field allows sufficient "max_length".

**Comment by ad-m** [comment]
What about truncate filename?

**Comment by adroffner** [comment]
Please, set the default filename **max_length** to at least 1024.

Filenames longer than 100 characters are far too common. My example below has 134 & Unix standards require at least 255 characters for a full path.

Your default location is "/mailbox_attachments/2017/02/22/" is 32 characters by itself.

ERROR: [django.security.SuspiciousFileOperation: 204] >> Storage can not find an available filename for
"/home/user/workspaces/mailbox_server/email_domains/media/mailbox_attachments/2017/02/22/ae4ee865c79b4f12a78e89c3bc337267_dBvw8WX.rtf"
Please make sure that the corresponding file field allows sufficient "max_length".

**Comment by coddingtonbear** [comment]
Your proposed changes for increasing the allowed filename length have been merged via #131 into the new `v5` branch where future work for the next major version of this library will be taking place.  It'll probably be a while before the next release is out, so I'd recommend just working off of your own fork for now, @adroffner.  Cheers!
