### ISSUE TITLE
Parsing the Reply-To header

### ISSUE THREAD

**Issue by TheMartinz** [coddingtonbear/django-mailbox#141]
is there a possibility to edit this library to parse the "reply-To" header.

I have an email system that has to reply to that header. I have tried to modify the source code but that keeps giving me errors.
Could you modify the source so it will parse the Reply-To header or can you explain to me how i can edit the source code myself.
Hope to hear from you soon.
(English not my native language. sorry if incorrect)

**Comment by erhan-** [comment]
Just work on the email object. Something like this works:

`msg_obj = message.get_email_object()
                        if "Reply-To" in msg_obj:
                            reply_to = msg_obj['Reply-To']`
