### ISSUE TITLE
we can haz nu release?

### ISSUE THREAD

**Issue by kmohrf** [coddingtonbear/django-mailbox#152]
hi :),

thank you for working on django-mailbox. would you consider releasing the current changes in the master branch as a new version? there’s a pull request fixing the Content-Transfer-Encoding KeyError bug somewhere in there and I would really like to use it without installing from git :).

here’s a lovely panda for your motivation:
![65bede438365a15839f746db8c46a496](https://user-images.githubusercontent.com/580226/31500396-95a5ef2a-af67-11e7-877c-71e68d44c260.jpg)

thank you!

**Comment by coddingtonbear** [comment]
Can do!  I'll try to find a few minutes this afternoon to push a new package.

**Comment by coddingtonbear** [comment]
Version 4.6.0 released.

**Comment by kmohrf** [comment]
thank you!
