### ISSUE TITLE
Django-mailbox delete all my emails

### ISSUE THREAD

**Issue by ArseniyBars** [coddingtonbear/django-mailbox#154]
I tried a django-mailbox with my work emails.(My company's admins haven't created a separate mailbox for backend yet). Django-mailbox download all the files successfully but when I logg in with Outlook find my incoming folder empty. When I logged in a server directly I saw the same thing. So now it's difficult for me to reply to collegues. Is there a way to return my emails back?

**Comment by ad-m** [comment]
The behavior you follow is consistent with the assumptions. The Django-mailbox retrieves the e-mail messages and then erases them to not download again the next time. Django-mailbox is not a typical mail program, and is a development library that makes it easy to process email messages in Django. 

A mailbox in that case plays the role of a message queue that needs to be processed. Objects processed from the queue are removed from the queue.

There is ```django_mailbox.models.get_email_object``` to get  ```email.message.Message``` instance representing the contents of this message and all attachments. Next to you can convert them to ``*.eml`` by ``Message.to_string``. Then you can upload them by IMAP or put in Maildir or any other way put in mailbox. It depends on individual preferences and configuration of the mail server.

**Comment by mgnisia** [comment]
As I also had this issue i created a gist with my solution:

https://gist.github.com/mgnisia/c8efb84d730a51b64d78439b35c8ea6e

```python
# Creating Function to write Email as EML File to Disk
def save_message(message_admin, request, queryset):
    i = 0
    for message in queryset.all():
        eml_content = message.get_email_object().as_bytes()
        file_name = f"some_file_path/{message.subject}_{i}.eml"
        print(file_name)
        with open(file_name, "wb") as outfile:
           outfile.write(eml_content)
        i += 1
        
        
# Registering the save_message command in the Admin panel
actions = [resend_message_received_signal, save_message]
```
