### ISSUE TITLE
Parse additional fields

### ISSUE THREAD

**Issue by erhan-** [coddingtonbear/django-mailbox#156]
Hello everyone,

I think it would be a great addition to parse additional fields like Date, Delivery-Time or also the Received chain.

**Comment by ad-m** [comment]
@erhan- , see #73. You can easily add OneToOne model and parse additional data in model by signals.

**Comment by erhan-** [comment]
At the moment I have just changed the model and added additional code to `_process_message`. 
So you mean I should create my own model e.g. AdditionMailInfo and put there the additional fields and a OneToOne relation to the Message object. Then when the signal is invoked, I will create the new AdditionalMailInfo Object, parse the fields and add them to this object +  the 1to1 relation?
I guess, this way I would not have to mess around directly with the django-mailbox code.

**Comment by ad-m** [comment]
Yes, using OneToOne relation model allow you to mess around directly with the django-mailbox code. I think this approach will allow us to keep the django-mailbox simple and universal.
