### ISSUE TITLE
send email to archive

### ISSUE THREAD

**Issue by olivtree** [coddingtonbear/django-mailbox#157]
In docs says: 

```
To archive email messages, add the archive folder name as a query parameter to the URI. For example, if your mailbox has a folder named myarchivefolder that you would like to copy messages to after processing, add ?archive=myarchivefolder to the end of the URI:
imap+ssl://youremailaddress%40gmail.com:1234@imap.gmail.com?archive=myarchivefolder
```

My URI looks like imap+ssl://myuser%40domain:xxxxxx@domain?archive=archived_djangomailbox
But when I get the emails, they are deleted and are not moved to the archived_djangomailbox folder. 
Am I doing something wrong? Is there something I do not understand?

Thanks

**Comment by ad-m** [comment]
@olivtree , please verify that this line is True https://github.com/coddingtonbear/django-mailbox/blob/master/django_mailbox/transports/imap.py#L133 and value of ```self.archive```.

**Comment by ad-m** [comment]
You can also verify that https://github.com/coddingtonbear/django-mailbox/blob/master/django_mailbox/models.py#L197

```
self.assertTrue(Mailbox.objects.get().archive, 'myarchivefolder')
self.assertTrue(Mailbox.objects.get().get_connection().archive, 'myarchivefolder')
```

**Comment by olivtree** [comment]
The value of self.archive is archived_djangomailbox (my archive folder). Is it supposed to be like this?

**Comment by ad-m** [comment]
@olivtree , are you sure this message disappears from the server? May your e-mail program ignore this folder? Can you check in another email program?

**Comment by olivtree** [comment]
I tried with a Gmail account and it works, but with a webmail account it does not work.
Thank you very much for the support.

**Comment by olivtree** [comment]
@ad-m sorry for bothering you. I saw through the browser developer tools that the folder is not called archived_djangomailbox but INBOX.archided_djangomailbox.
django-mailbox works just fine
Thanks for the support
