### ISSUE TITLE
Text attachments are returned as email body content as well as an attachment

### ISSUE THREAD

**Issue by dborin** [coddingtonbear/django-mailbox#169]
It appears that only Content-Type is used to determine the contents of the message (aka body).  Therefore, for plaintext emails with text attachments, Content-Type: text/plain is what is used to find the contents of the email.  You need to also include Content-Disposition: inline as part of the search/sort criteria, so as to not include the contents of text attachments in the message body

**Comment by ad-m** [comment]
@dborin do you can provide test message as ``*.eml`` format (with attachment)? It would be helpful to develop a test case to protect against future errors.

**Comment by dborin** [comment]
I'm using mutt as my mail client, so can't export as .eml file.  Sorry

It's just a simple message with a .txt file as an attachment.

**Comment by ad-m** [comment]
You can probably get to e-mails using another e-mail program as well. I am interested in a full e-mail with headlines (of course, anonymized). It means ``*.eml`` message. Alternatively, use the Python standard library to IMAP protocol or copy it directly from Maildir.

If you are unable to provide such a message - I will try to develop it myself.

**Comment by dborin** [comment]
Here's the mbox format

From dhuser1@example.com Tue Feb  6 23:27:56 2018
Date: Tue, 6 Feb 2018 23:27:56 +0000
From: Dee AitchOne <dhuser1@example.com>
To: dhmail@example.com
Subject: Do you see 3? [ARTS]
Message-ID: <20180206232756.GA31740@designhub-test04.c.designhub-144114.internal>
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="liOOAslEiF7prFVr"
Content-Disposition: inline
User-Agent: Mutt/1.5.20 (2009-12-10)
Status: RO
Content-Length: 918
Lines: 41


--liOOAslEiF7prFVr
Content-Type: text/plain; charset=us-ascii
Content-Disposition: inline

nope`

--liOOAslEiF7prFVr
Content-Type: text/plain; charset=us-ascii
Content-Disposition: attachment; filename="manylines.txt"

Mary had a little lamb
Who's fleece was white as snow
Now is the time
For all good men
To come to the aide of their country
The quick brown fox
jumped over the lazy dog
Mary had a little lamb
Who's fleece was white as snow
Now is the time
For all good men
To come to the aide of their country
The quick brown fox
jumped over the lazy dog
Mary had a little lamb
Who's fleece was white as snow
Now is the time
For all good men
To come to the aide of their country
The quick brown fox
jumped over the lazy dog
Mary had a little lamb
Who's fleece was white as snow
Now is the time
For all good men
To come to the aide of their country
The quick brown fox
jumped over the lazy dog

--liOOAslEiF7prFVr--

**Comment by dborin** [comment]
Added an mbox to the issue.  Hopefully that works for you

**Comment by ad-m** [comment]
There is some tests for that: https://github.com/coddingtonbear/django-mailbox/blob/master/django_mailbox/tests/test_process_email.py#L396-L403

**Comment by dborin** [comment]
That test looks like it's getting a text based attachment, not whether or
not it's adding the contents of the text file to the returned message's
body.

**Comment by dborin** [comment]
BTW -- Thanks for looking at this so quickly.  Our team is having to do
some hacks on our end to parse out the extraneous message body, so fixing
this would be really helpful.

**Comment by ad-m** [comment]
I will try to identify the topic this week and suggest a solution. Today I will work on it for some time also. If it is urgent for you, the patch is always welcome. This is a non-commercial, open source project.

**Comment by dborin** [comment]
I'll see if I can figure it out, but being wholly unfamiliar with the repo
(I'm the test guy, our devs are the ones using it), you'll probably be able
to figure it out way faster than me.

Thanks again.

**Comment by coddingtonbear** [comment]
I'm _betting_ that the problem is that we're not checking `Content-disposition` here: https://github.com/coddingtonbear/django-mailbox/blob/master/django_mailbox/utils.py#L105 , and instead just returning any parts with matching mimetypes.

**Comment by dborin** [comment]
Yeah, that's what I said in the original bug submission.  You're just
grepping for  Content-Type

**Comment by coddingtonbear** [comment]
This was, unless I'm mistaken, fixed as part of 4.7.1.
