### ISSUE TITLE
DJANGO_MAILBOX_default_charset needs to be DJANGO_MAILBOX_DEFAULT_CHARSET

### ISSUE THREAD

**Issue by neural22** [coddingtonbear/django-mailbox#171]
Dear all,
I have found a bug related to DJANGO_MAILBOX_default_charset settings. LazySettings for Django configurations are properly loaded only if they are in uppercase. Right now DJANGO_MAILBOX_default_charset is not loaded properly, so it cannot be specified something different to "iso8859-1".
This can be solved changing DJANGO_MAILBOX_default_charset to DJANGO_MAILBOX_DEFAULT_CHARSET in utils.
This bug cause crashes every time you try to write a message with non latin-1 characters...
Please, can someone take a look into this problem?

**Comment by pfouque** [comment]
Hi, 
AFAIk django settings name are more a convention and it should work if you name your setting exactly like it is expected: "DJANGO_MAILBOX_default_charset".
But I agree it's not intuitive, and this setting is not even documented...
I saw the [PR 267](https://github.com/coddingtonbear/django-mailbox/pull/267) trying to fix that, but it's not retro-compatible yet

**Comment by pfouque** [comment]
Fixed on master branch (not released yet)

> I saw the https://github.com/coddingtonbear/django-mailbox/pull/267 trying to fix that, but it's not retro-compatible yet

There is no retro compatibility to implement since the old format was purely ignored by django
