### ISSUE TITLE
How to automatically recieve messages as they arrive in my inbox?

### ISSUE THREAD

**Issue by pycampers** [coddingtonbear/django-mailbox#173]
I have setup django-mailbox successfully using gmail imap.

I tried `manage.py getmail` and it worked flawlessly.

But how can i make it listen for all incoming messages?

I have setup a signal and loaded it in my `AppConfig's ready()` method but it doesn't seem to respond to new messages in my inbox

Here is my apps.py
```
from django.apps import AppConfig


class FeedsConfig(AppConfig):
    name = 'feeds'

    def ready(self):
        import feeds.signals
```
Here is my signals.py
```
from django.dispatch import receiver
from django_mailbox.signals import message_received

@receiver(message_received)
def dance_jig(sender, message, **args):
    print("I just recieved a message titled %s from a mailbox named %s" % (message.subject, message.mailbox.name,))
```
P.S. I have confirmed that the `signals.py` file is loaded by printing a message at the start of `signals.py`

**Comment by coddingtonbear** [comment]
The variety of methods of fetching incoming e-mails automatically are discussed here: http://django-mailbox.readthedocs.io/en/latest/topics/polling.html; is there a specific question you have, or did you just not find the doc?

**Comment by pycampers** [comment]
I was trying to make [this](http://django-mailbox.readthedocs.io/en/latest/topics/signal.html) work, but my signal doesn't seem to fire with new emails that i recieve.

**Comment by ad-m** [comment]
Did you load signals in AppConfig?

08.03.2018 12:58 PM "pycampers" <notifications@github.com> napisał(a):

**Comment by pycampers** [comment]
Please read my question, i wrote 

> I have setup a signal and loaded it in my AppConfig's ready() method

&

> P.S. I have confirmed that the signals.py file is loaded by printing a message at the start of signals.py

**Comment by coddingtonbear** [comment]
Just in case there's some confusion about how things work -- that signal fires when your app has received a message via either a pipe or polling; which of those methods are you using?

**Comment by pycampers** [comment]
@coddingtonbear I am not sure what you're talking about.

It's a simple email, i sent using gmail.

What is that pipe / polling method you talk about? Please redirect me to the docs if I missed something.

P.S. sorry for no-reply, I forgot to check mail.

**Comment by coddingtonbear** [comment]
I'm sorry if I wasn't clear above, but this is the page of the docs you need to familiarize yourself with: http://django-mailbox.readthedocs.io/en/latest/topics/polling.html .

What you need to do is implement one of the four ways of "Getting incoming mail" (see the above doc); your options include running `get_new_mail` in your code somewhere, clicking on "Get new mail" in the django admin, running the `getmail` management command, or receiving your mail from Exim4 or Postfix via a pipe.  The signal you're mentioning above fires when Django-mailbox processes a message received via one of those four methods.

Just to give you a hint -- if you're receiving mail into a Gmail inbox, you won't be able to use the last method ("Receiving mail directly from Exim4 or Postfix via a pipe").

**Comment by pycampers** [comment]
That makes it crystal clear. Thanks.

Btw, I could probably run `get_new_mail` as a celery beat task, right?

**Comment by coddingtonbear** [comment]
That's one option, yes.
