### ISSUE TITLE
How to create a mailbox using details added in admin 

### ISSUE THREAD

**Issue by kieransnapes** [coddingtonbear/django-mailbox#176]
I'm pretty new to django so bear with me if this is a silly question.

How do I go about creating a mailbox using the details I've already populated in the admin area?
I have connected a gmail account and can verify receiving mail within the admin page,

However I'm struggling to create a new mailbox using one that already exists in my model. 
This is how i thought it would go - 
`   mailbox = Mailbox.active_mailboxes.get('MailboxName')  `
 `   mailbox.get_new_mail `

Could you perhaps provide an example of how i'd create a mailbox in the code using pre-existing mailbox details in the database?

Cheers

**Comment by coddingtonbear** [comment]
I'm not totally sure I understand the question, but it sounds like you might be hoping to create multiple mailboxes for a single e-mail address.  The way this package works is by consuming all mail found in a given e-mail account and importing it into your Django app.  The relationship between the "Mailbox" object and an e-mail address is probably always going to be one-to-one. 

Am I misunderstanding your question?

**Comment by ad-m** [comment]
>  The relationship between the "Mailbox" object and an e-mail address is probably always going to be one-to-one.

It's definitely not true. I am using catch-all e-mail address, so I have unlimited e-mail address for one mailbox. There is possible to use forwards (aliases) too, so multiple e-mail address to one mailbox.

GMail support some tricks too: http://www.htstechtips.com/2010/09/24/multiple-google-email-addresses-one-gmail-account/

**Comment by coddingtonbear** [comment]
Oh, that's true -- I still think of those catch-all e-mail addresses that google lets you use as the "same" e-mail address, though.  What I should've said above, were I speaking more precisely, is that the relationship between an e-mail account and a Mailbox object in this app will probably always be one-to-one.

**Comment by kieransnapes** [comment]
I just want to know how to get_new_mail in my code using the mailbox I've already defined in the django admin like so:
https://gyazo.com/06ab2b8b779cf55ec37bb83bfe1eca4e

Can i access the details defined here within my code? Or do I have to define a new mailbox in my code (populating it with the URI and everything)
