### ISSUE TITLE
Is support for gmailapi+ssl planned?

### ISSUE THREAD

**Issue by pablodiazgutierrez** [coddingtonbear/django-mailbox#185]
I work on a system that responds to PUBSUB Gmail requests, and we use a gmailapi+ssl: URI to access the messages. Starting a couple of days ago, this stopped working and we get a `local variable 'conn' referenced before assignment` error.

Do you think this protocol will be supported at some point?

**Comment by coddingtonbear** [comment]
Sort of curious about where `gmailapi` came from; I'm [unfamiliar with that mailbox type](http://django-mailbox.readthedocs.io/en/latest/topics/mailbox_types.html).

**Comment by ad-m** [comment]
@coddingtonbear , https://github.com/coddingtonbear/django-mailbox/blob/e0687380a1d6cf3aa0958c8cf5d1d532934d8d49/django_mailbox/models.py#L226 returns "conn" even in "conn" not set on unknown backend.

**Comment by coddingtonbear** [comment]
Yep!  We should definitely be raising an exception when no matching transport was found.  I wonder, though, if @pablodiazgutierrez might have better luck using the `gmail+ssl://` transport?

**Comment by pablodiazgutierrez** [comment]
I'm able to use the IMAP protocol, but this legacy code was (somehow) working well until 2 days ago...

**Comment by coddingtonbear** [comment]
I'm quite confused -- as far as I can tell, there has never been a transport named `gmailapi`; I might be misunderstanding, but are you suggesting that you were successfully using such a URL in the past?  If so, I wonder if you might've previously been using a fork?

**Comment by pablodiazgutierrez** [comment]
Sorry about all this confusion. It turns out we were using a local fork with a non-standard setup flow. Thanks everyone for the feedback. I guess if there's one thing that can still be applied to the project is some more informative way to indicate that a given URI transport protocol is not supported.
