### ISSUE TITLE
how can I customize where the module stores the attachments that it receives?

### ISSUE THREAD

**Issue by modernNeo** [coddingtonbear/django-mailbox#190]

**Comment by coddingtonbear** [comment]
Depending on what you mean by "where", the answers differ:

* If you mean on the filesystem, you should look at the setting [`MEDIA_ROOT`](https://docs.djangoproject.com/en/2.0/ref/settings/#media-root) and the setting [`DJANGO_MAILBOX_ATTACHMENT_UPLOAD_TO` discussed in django-mailbox' docs](DJANGO_MAILBOX_ATTACHMENT_UPLOAD_TO
).
* If you mean somewhere _outside_ of your filesystem (i.e. an S3 bucket), you should look at [`DEFAULT_FILE_STORAGE`](https://docs.djangoproject.com/en/2.0/ref/settings/#default-file-storage) and, maybe, the module [django-storages](https://github.com/jschneier/django-storages).

Most of the questions around how that works are really not specific to this library, and more specific to how Django itself handles user-provided assets, but if you have further questions, I might be able to nudge you in the right direction if you [find me on the gitter.im channel](https://gitter.im/coddingtonbear/django-mailbox).

**Comment by modernNeo** [comment]
Where you meaning to link [DJANGO_MAILBOX_ATTACHMENT_UPLOAD_TO](https://django-mailbox.readthedocs.io/en/latest/topics/appendix/settings.html?highlight=DJANGO_MAILBOX_ATTACHMENT_UPLOAD_TO) ?

**Comment by coddingtonbear** [comment]
Yep!

**Comment by modernNeo** [comment]
If I wanted to modify that, I would have to modify the actual module inside the /usr/lib folder, is that what you recommend I do if I want to change where the media is downloaded to on the filesystem?

I would prefer to not use gitter.im if that is OK with you.

**Comment by coddingtonbear** [comment]
As far as I'm aware, you cannot. modify that to point at something outside of `MEDIA_ROOT` -- that's a limitation of Django.  I think at this point, you'd be better served by just checking out the django docs for how a field field works.  Good luck!

**Comment by modernNeo** [comment]
thanks @coddingtonbear , I am a newbie to Django and didnt realize that I could specify the settings in that link within the settings.py, twas exactly what I needed 👍

**Comment by coddingtonbear** [comment]
Awesome; I'm glad you figured it out!  Feel free to ask other questions on the gitter channel if you bump into them, too!

Cheers!
