### ISSUE TITLE
would it be possible to add a field to the emails containing the date the email was recieved?

### ISSUE THREAD

**Issue by modernNeo** [coddingtonbear/django-mailbox#191]
At this time, the only date-time field for the emails that I can see are the processed time but I am in need of a field that has the time that email was sent.  

I would modify the module myself but I am a newbie to Python and don't currently have the time to learn how to modify it without breaking it.  
  
I have written up the code that can be used to extract the date from the email body however so that you guys dont have to do much coding [hopefully]. But just an fyi, I have only tested it with the emails the module extract from a gmail account.

https://gist.github.com/modernNeo/374e6e62bdecbfdafa3be5e5c7fe7608

**Comment by leewesleyv** [comment]
Not sure if this is what you need but you can get the date from the headers using this:

`Message.get_email_object().get('date')`

Which will return the date from the email headers (e.g. 'Mon, 9 Jul 2018 16:32:51 +0200')

**Comment by ad-m** [comment]
See https://github.com/coddingtonbear/django-mailbox/issues/73

**Comment by modernNeo** [comment]
@leewesleyv thanks, that was helpful but it would still be nice to get a field for the date from the email like there is for processed. I notice that rulzart proposed the same thing in PR 73 that @ad-m linked but not sure why that proposition was ultimately rejected?

**Comment by ad-m** [comment]
@modernNeo using the one-to-one relationship, you can achieve the same without having to modify the data model for all existing users.
