### ISSUE TITLE
documentation seems to be wrong in the "POP3 and IMAP Mailboxes" config section.

### ISSUE THREAD

**Issue by modernNeo** [coddingtonbear/django-mailbox#193]
Regarding https://django-mailbox.readthedocs.io/en/latest/topics/mailbox_types.html#pop3-and-imap-mailboxes

It says

> For a verbose example, if you have an account named `youremailaddress@gmail.com` with a password of `1234 `on GMail, which uses a IMAP server of `imap.gmail.com` (requiring SSL) and you would like to fetch new emails from folder named `Myfolder `and archive them after processing into a folder named `Archived`, you would enter the following as your URI:

But then the uri is just
`imap+ssl://youremailaddress%40gmail.com:1234@imap.gmail.com?archive=Archived`

There is no mention of `Myfolder` in there. Was that a typo?

**Comment by modernNeo** [comment]
@ad-m sorry for the ping but can I get some insight on this?

**Comment by ad-m** [comment]
yes, missing specifying the ```folder``` URI query parameter. Could you provide PR to fix that?

**Comment by modernNeo** [comment]
hopefully this PR is sufficient, let me know if I missed any steps https://github.com/coddingtonbear/django-mailbox/pull/216

**Comment by modernNeo** [comment]
PR merged
