### ISSUE TITLE
Missing migration in version 4.7.1

### ISSUE THREAD

**Issue by anuj-reef** [coddingtonbear/django-mailbox#195]
There is a missing migration in current version due to which django reports error to create migrations. Please fix it.

If I run `python manage.py makemigrations` - I get the following:

```
Migrations for 'django_mailbox':
  /home/anuj/.virtualenvs/xxxxxx/lib/python3.6/site-packages/django_mailbox/migrations/0007_auto_20181126_0403.py
    - Change Meta options on mailbox
    - Change Meta options on message
    - Change Meta options on messageattachment
```

**Comment by k0ssi** [comment]
Migrations for 'django_mailbox':
  /usr/local/lib/python3.5/dist-packages/django_mailbox/migrations/0007_auto_20190219_1359.py
    - Change Meta options on mailbox
    - Change Meta options on message
    - Change Meta options on messageattachment
    - Alter field active on mailbox
    - Alter field outgoing on message
Traceback (most recent call last):
  File "/home/vagrant/.pycharm_helpers/pycharm/django_manage.py", line 59, in <module>
    run_command()
........
........
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.5/dist-packages/django_mailbox/migrations/0007_auto_20190219_1359.py'
