### ISSUE TITLE
ImportError: No module named 'django_mailbox'

### ISSUE THREAD

**Issue by raficsedu** [coddingtonbear/django-mailbox#196]
I am running my Django project in virtual environment. I have installed the django mailbox as defined in documentation,
pip install django_mailbox
And set in settings.py file. But i am getting importerror while i am trying to migrate.
![error](https://user-images.githubusercontent.com/7780072/49417012-4e97c080-f7a6-11e8-844c-f4e44932a2c0.jpg)

**Comment by coddingtonbear** [comment]
That means, of course, that although you may have installed `django-mailbox` into _a_ virtualenv, the virtualenv in which your migration is being executed is not _that_ virtualenv.

**Comment by raficsedu** [comment]
I see, can you help me to give the procedure by which i can run migrations from the desired virtual env.

**Comment by coddingtonbear** [comment]
All you should have to do is activate your virtualenv from the shell in which you're running migrations; I think you might be able to consult with the virtualenv documentation for more details, though!

**Comment by raficsedu** [comment]
Thank you Coddingtonbear, it solves my problem.
