### ISSUE TITLE
django-mailbox master (post 4.7.1) says `object of type 'generator' has no len()`

### ISSUE THREAD

**Issue by ses4j** [coddingtonbear/django-mailbox#203]
The following:

```
messages = mailbox.get_new_mail()
num_msgs = len(messages)
```

works on 4.7.1 but on master says this:

`object of type 'generator' has no len()`

**Comment by ad-m** [comment]
Yes, because we start use generator there. If you don't care about memory you can write:
```
messages = list(mailbox.get_new_mail())
num_msgs = len(messages)
```

**Comment by ad-m** [comment]
Mentioned in changelog.
