### ISSUE TITLE
Broken in 4.8.0..?

### ISSUE THREAD

**Issue by xeor** [coddingtonbear/django-mailbox#207]
After upgrading to `4.8.0`, we django-mailbox stopped receiving mails from imap. Is this a known issue? There was no errors.

Using `imap+ssl://...` with `get_new_mail` and the first arg being a function to decide if the mail should be downloaded or not.

Downgrading to `4.7.1` seams to fix the issue..

I'll test more later in dev, this is the initial report.

I also can't find much info about 4.8.0 in this repo. What is building it on pypi? https://pypi.org/project/django-mailbox/#history

**Comment by ad-m** [comment]
Did you reference ```get_new_mail``` directly in your codebase? How? According to the changelog (pushed), it has now become a generator.

**Comment by xeor** [comment]
Yea.. I noticed that as well.. I'll wrap it in a list() to fix it :)

**Comment by ad-m** [comment]
I would like to warn you that this may cause the application to be unstable if you receive a large amount of messages with attachments in a short period of time. It recommends consuming the iterator and processing one after the other.

**Comment by xeor** [comment]
Ok, thanks.. I'll go through how it works and see if I can restucture..
