### ISSUE TITLE
Missing migrations on 4.8.0?

### ISSUE THREAD

**Issue by vesatoivonen** [coddingtonbear/django-mailbox#208]
I'm not sure where the confusion is, but based on the commit history i'd expect the latest migration file (0008_auto_20190219_1553.py) to be included in 4.8.0 since it was added before the version bump from 4.7.1.
Still, the package from pypi or tag `4.8.0` doesn't seem to contain said migration file.

**Comment by ad-m** [comment]
Fixed in 4.8.1

**Comment by vesatoivonen** [comment]
Indeed it is, thanks.
