### ISSUE TITLE
No Token available in python-social-auth

### ISSUE THREAD

**Issue by entissar12** [coddingtonbear/django-mailbox#211]
Hello,
After installing django mailbox, and adding a new active mailbox as below:
name : my gmail address
url: gmail+ssl://myaddress%40gmail.com:oauth2@imap.gmail.com?archive=Archived
When I run

>  python manage.py getmail

I get the following error:
`No Token available in python-social-auth for my gmail address`

Can anyone help me please?

**Comment by ad-m** [comment]
> To handle the handshake and storing the credentials, use python-social-auth.

https://django-mailbox.readthedocs.io/en/latest/topics/mailbox_types.html#gmail-imap-with-oauth2-authentication

See https://github.com/coddingtonbear/django-mailbox/blob/master/django_mailbox/transports/gmail.py#L38 , https://github.com/coddingtonbear/django-mailbox/blob/26786a0b3200515d490ecb69e1bc5b86efcc0ffb/django_mailbox/google_utils.py#L30 .

**Comment by RealNicolasBourbaki** [comment]
@entissar12 May I ask how did you solve the problem? I have the same issue but I am pretty sure I have python-social-auth installed

**Comment by pfouque** [comment]
Ok the documenation is not so clear on that, but basically you have multiple options:
- [BasicAuth directly in the mailbox url](https://django-mailbox.readthedocs.io/en/latest/topics/mailbox_types.html#gmail-imap-with-oauth2-authentication): `imap+ssl://<url_encoded_email_address>:<password>@imap.gmail.com` (Don't forget to replace with your credentials)
- Python Social Auth: It will require that [GOOGLE_OAUTH2](https://python-social-auth.readthedocs.io/en/latest/backends/google.html#google-oauth2) is working and that you already connected with this email address. Then you can configure the mailbox URL to be `imap+ssl://<url_encoded_email_address>@imap.gmail.com?archive=myarchivefolder`

**Comment by pfouque** [comment]
I'm closing that issue because it's really old but feel free to re-open if needed
