### ISSUE TITLE
messages stored do not have html property

### ISSUE THREAD

**Issue by modernNeo** [coddingtonbear/django-mailbox#213]
I notice sometimes, when django-mailbox consumes the email from the gmail I set it up with, some of the emails do not have their `html` property populated, only their `text` property. Is this expected behavior?

I need the `html` property field as I would like to display the contents of the email with the hyperlinks set.

**Comment by ad-m** [comment]
Are you sure the message was sent by the user using HTML? The user does not need to submit the HTML version, and then the django-mailbox does not offer the HTML version.

**Comment by modernNeo** [comment]
I was not aware that the html version does not always exist by default
