### ISSUE TITLE
From the Django Admin, using the ‘Get New Mail’ action from the action dropdown not working

### ISSUE THREAD

**Issue by Lifechess** [coddingtonbear/django-mailbox#229]
i'm using django-mailbox 4.8.1 and my problem is admin action get_new_mail not working but from the shell it is working and i don't have any error.

**Comment by ad-m** [comment]
See #228 and support review pull request (verify changes, review code).

**Comment by Lifechess** [comment]
thanks for the tip! it work fine.
I hope there be a new version release for that because i have to ingrate the app in my code  for production

**Comment by pfouque** [comment]
Should be fixed by #228
