### ISSUE TITLE
message_received signal not firing?

### ISSUE THREAD

**Issue by joshuakoh1** [coddingtonbear/django-mailbox#233]
/base/myapp/__init__.py
```
default_app_config = 'myapp.apps.MyAppConfig'
```
/base/myapp/apps.py
```
from django.apps import AppConfig
class MyAppConfig(AppConfig):
    name = 'myapp'
    def ready(self):
        import myapp.signals
```
/base/myapp/signals.py
```
from django_mailbox.signals import message_received
from django.dispatch import receiver
@receiver(message_received)
def handle_new_email(sender, message, **args):
    print('Recieved a message titled %s from a mailbox named %s' % (message.subject, message.mailbox.name, ))
    otherfunction(sender, message, **args)
    print('Done')
```
/base/settings.py
```
INSTALLED_APPS = [
    'myapp',
]
```

**Comment by ad-m** [comment]
Are you running `getmail` command?

**Comment by joshuakoh1** [comment]
The mail was being added to the DB but the signal wasn't firing.

Funny story. Spent many hours breaking stuff trying to make it work. Went for a walk and had a crazy idea. 

Under installed apps, I had myapp under django_mailbox. Switched it around myapp first and django_mailbox below and it's working now. Signals frustrate me so much.

**Comment by abratchik** [comment]
I have a similar problem - message_received is not firing when I'm receiving emails using  getmail. I trigger 'manage getmail' using cron  job every minute. Emails are appearing in the admin view but no signals are fired.
