### ISSUE TITLE
documention not updating

### ISSUE THREAD

**Issue by modernNeo** [coddingtonbear/django-mailbox#237]
I see 2 different PRs that don't seem to have had any actual effect on the documentation:

[PR-212](https://github.com/coddingtonbear/django-mailbox/pull/216) did not change the url `imap+ssl://youremailaddress%40gmail.com:1234@imap.gmail.com?archive=Archived` in section [POP3 and IMAP Mailboxes](https://django-mailbox.readthedocs.io/en/latest/topics/mailbox_types.html#pop3-and-imap-mailboxes)

[PR-221](https://github.com/coddingtonbear/django-mailbox/pull/221) did not add the url `imap+ssl://youremailaddress%40gmail.com:1234@imap.gmail.com?archive=myarchivefolder&folder=MyFolder` to [Specifying an archive folder](https://django-mailbox.readthedocs.io/en/latest/topics/mailbox_types.html#specifying-an-archive-folder)

**Comment by ad-m** [comment]
What do you propose?

**Comment by modernNeo** [comment]
unsure what you mean. I am just pointing out the fact that the PRs that are supposed to be updating the documentation are not updating the documentation. I assumed that that needs to be addressed and fixed.

**Comment by coddingtonbear** [comment]
Hrm; looking at the rtd build for this, it looks like it has been broken for about a year: https://readthedocs.org/projects/intheam/builds/8282038/

**Comment by coddingtonbear** [comment]
All fixed, @modernNeo ; thanks for the heads-up!
