### ISSUE TITLE
get_new_mail from mailboxes inbox: where in mailbox are the loaded messages located?

### ISSUE THREAD

**Issue by mondomeme** [coddingtonbear/django-mailbox#239]
Hello,

I'm trying to develop a mail management system using Django and django mailbox.
 I have a set of same domain mailboxes, for example : mark@dog.com, emily@dog.com. The mailboxes have all the same configuration: imap, tls, host server.

When I load new messages with the `get_new_mail` function, the messages are correctly loaded, but when I'm trying to access to a mailbox I see no message.  

After searching for several hours, I see for a mailbox the loaded messages are marked as 'deleted', instead for another one all messages disappeared.

I don't understand the two different behaviors.

**Comment by ad-m** [comment]
> The Django-mailbox retrieves the e-mail messages by eg. IMAP, POP and then **erases them to not download again the next time**. Django-mailbox is not a typical mail program, and is a development library that makes it easy to process email messages in Django. A mailbox in that case plays the role of a message queue that needs to be processed. **Messages processed from the queue are removed from the queue.**

https://django-mailbox.readthedocs.io/en/latest/

**Comment by mondomeme** [comment]
@ad-m thank you for reply. I understand the messages are erased, but I don't understand for two different mailbox with same configuration the message are definitevely erased or marked and stored as 'Deleted'.

**Comment by ad-m** [comment]
Ask your mailbox provider. Different mailbox providers handle delete on different way.

**Comment by mondomeme** [comment]
I figured out why the mailbox messages haven't been deleted: the mailbox has so much messages in inbox and running of `get_new_mail `crashed. In fact I see duplicated records in `django_mailbox_message` table. The other mailbox has much less messages. 

The problem now is the same of #212 issue.

**Comment by ad-m** [comment]
Closed as duplicate.
