### ISSUE TITLE
ImportError: cannot import name ‘python_2_unicode_compatible’ from ‘django.utils.encoding’ (/opt/venv/lib/python3.8/site-packages/django/utils/encoding.py)

### ISSUE THREAD

**Issue by mishaelg** [coddingtonbear/django-mailbox#240]
Hi,
There is an import error in one of the files, I think at /django_mailbox/models.py line 31 the line should change from 'django.utils.encoding import python_2_unicode_compatible' to 'from six import python_2_unicode_compatible'.

Thanks in advance,
Mishael

**Comment by ad-m** [comment]
We drop support for Python 2, so we don't need `python_2_unicode_compatible` at all. Could you provide PR to fix that?

**Comment by mishaelg** [comment]
I see now it was already removed in github. Is it possible that "pip install django-mailbox" doesn't install the latest version? I think it just a matter of updating the release.

**Comment by valerytar** [comment]
Same issue here!

**Comment by mishaelg** [comment]
Is there a way I can assist in solving this problem?

**Comment by ad-m** [comment]
@mishaelg , could you prepare changelog for new release?

**Comment by mishaelg** [comment]
Sure, what is the commit id for current release?

**Comment by ad-m** [comment]
We tag each release, so you can check by tag.

**Comment by mishaelg** [comment]
I was about to create a new pr when I noticed you already have one for release 5.0 - https://github.com/coddingtonbear/django-mailbox/pull/223

**Comment by ad-m** [comment]
I have time 11.11.2020 to release it. Take look and provide any input.

**Comment by mishaelg** [comment]
Seems fine, I would just add to changelog that you dropped support for python 2

**Comment by variable** [comment]
I see tag 5.0.0 since 2020 but not on pypi, any ideas?

**Comment by pfouque** [comment]
Fixed with the last release
