### ISSUE TITLE
Error when upgrading to Django 4.0

### ISSUE THREAD

**Issue by sanderroosendaal** [coddingtonbear/django-mailbox#248]
File "/home/sander/python/rowsandall/venv/lib/python3.8/site-packages/django_mailbox/models.py", line 31, in <module>
    from django_mailbox.signals import message_received
  File "/home/sander/python/rowsandall/venv/lib/python3.8/site-packages/django_mailbox/signals.py", line 3, in <module>
    message_received = Signal(providing_args=['message'])
TypeError: __init__() got an unexpected keyword argument 'providing_args'

**Comment by ad-m** [comment]
It's deprecated and we don't released yet version for Django 4.0. Could you provide PR for that?

**Comment by Haakonoeyen** [comment]
This solved the problem for me.

In C:\Users\USERNAME\.virtualenvs\autotek-a3gt69_I\lib\site-packages\django_mailbox\signals.py

Simply change `message_received = Signal(providing_args=['message'])` to `message_received = Signal()`

**Comment by ad-m** [comment]
@Haakonoeyen there is PR for that  #249 . Do you like take over it to make a new version of django-mailbox happen?

**Comment by Haakonoeyen** [comment]
I'd love to, but I'm new to github so I'm gonna need a little help getting started. What will I have to do?

**Comment by ad-m** [comment]
@Haakonoeyen you need pull pull request #249 (see https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally ), prepare outlined changes and create a new pull request ( https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request ) with all required changes. I think from a code perspective, these changes are minimal, so it's a perfect case to start working with open-source on GitHub

See also https://github.com/firstcontributions/first-contributions and https://opensource.guide/how-to-contribute/ .

**Comment by humbertolopezleon** [comment]
@ad-m I would like to know if you have an upcoming date to release support for Django 4

**Comment by Pietro395** [comment]
> @ad-m I would like to know if you have an upcoming date to release support for Django 4

Version 4.9.0 with Django 4 support has been released
