### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by jsenecal** [coddingtonbear/django-mailbox#250]
Hello all, just checking in to see if I should use this project in a new project of mine.

I see that a lot of issues and pull requests have had no answers from @coddingtonbear (are there other maintainers?) and that the last commit is from two years ago. Is this "officially" dead ?

**Comment by coddingtonbear** [comment]
There are many active contributors, @jsenecal, including @ad-m.  Unfortunately, we're all volunteers so no guarantees can be made about when particular fixes or changes are made.  If you'd like to improve matters, you're welcome to help out!

**Comment by jsenecal** [comment]
Ohhh I was not complaining, I am myself very happy to help! Glad to see that some people are still around. Problem is that many forked this project to fix things on their own which is great but without the ability to bring these changes back to the project, well, it doesn't help the project but rather dilutes it.

Anyhow, thanks for your answer :)
