### ISSUE TITLE
Microsoft Exchange Server/Outlook deprecating basic auth (IMAP and POP)

### ISSUE THREAD

**Issue by junaid-malim-imp** [coddingtonbear/django-mailbox#256]
there is no other supported protocol in this lib for outlook, it only supported basic mailbox like IMAP and POP, are you planning to add OAuth for outlook too?
becasue this lib won't be usable with exchange servers after December 2022.

if you want to [read up](https://techcommunity.microsoft.com/t5/exchange-team-blog/basic-authentication-deprecation-in-exchange-online-september/ba-p/3609437) on the changes.

**Comment by ptav** [comment]
Hi junaid, how did you resolve the above issue? I discovered that Microsoft will extend support for another 3 months until the end of March. But that is fast approaching and still don't have a solution. There are PR's that address this issue but require further testing. The original programmer who still manages the repo is looking for testers and volunteers are welcomed

**Comment by skar395** [comment]
Hi junaid, O365 support has been merged!
give it a look :)
