### ISSUE TITLE
New Release With Office 365 API

### ISSUE THREAD

**Issue by Roman-Hnatenko** [coddingtonbear/django-mailbox#274]
Hey Guys,
Thanks for your app.

Could you please a new release with the Office 365 API?

Last release was 3 years ago(

**Comment by Pietro395** [comment]
Hi, you're right, in the meantime, however, you can install the development version:

`pip3 install git+https://github.com/coddingtonbear/django-mailbox.git`

**Comment by Roman-Hnatenko** [comment]
Thank you @Pietro395 for quick feedback

**Comment by Pietro395** [comment]
@Roman-Hnatenko release 4.9.0 has been released
