### ISSUE TITLE
Error migrating

### ISSUE THREAD

**Issue by jslovern391** [coddingtonbear/django-mailbox#275]
TypeError: Signal.__init__() got an unexpected keyword argument 'providing_args'

Have a mail-in-a-box server and want to import email messages into django.

**Comment by Pietro395** [comment]
Hello, what django version are you using?

**Comment by jslovern391** [comment]
4.2

**Comment by Pietro395** [comment]
> 4.2

Atm django mailbox doesn't support Django 4

**Comment by jslovern391** [comment]
well that would do it - any plans to do so?

**Comment by coddingtonbear** [comment]
Yes!  I just need folks to review the open PR adding that and try the changes out in their own environments -> https://github.com/coddingtonbear/django-mailbox/pull/249

**Comment by jslovern391** [comment]
Ok I am new to django and git so if you can help me with this I would be happy to test it.  I need this functionality for my app.

**Comment by abhishekc-bhs** [comment]
> TypeError: Signal.**init**() got an unexpected keyword argument 'providing_args'
> 
> Have a mail-in-a-box server and want to import email messages into django.

Downgrade to Django 3.2 and it works. 3.2 LTS supported till 2024 first quarter. 

Hope this helps :)

**Comment by Pietro395** [comment]
@jslovern391 release 4.9.0 has been released
