### ISSUE TITLE
when will the new code be released?

### ISSUE THREAD

**Issue by modernNeo** [coddingtonbear/django-mailbox#276]
looking at pypi, I see that the last release happened about 3 years ago at this point: https://pypi.org/project/django-mailbox/#history

Even though there are 2 PRs that were merged in 2022 and 2023. Will there ever be another pypi release or do we need to resort to other ways of importing the module?

**Comment by pfouque** [comment]
@coddingtonbear are you looking for help to maintain this repository?

**Comment by coddingtonbear** [comment]
Yes -- definitely.  On a few of the PRs, I've indicated that I need somebody to verify changes in actual, real environments that receive real e-mail to verify that those PRs do indeed work and not cause their own bugs.  I do not currently and certainly won't in even the remote future be able to find the time to do those verifications myself.

**Comment by Pietro395** [comment]
> Yes -- definitely. On a few of the PRs, I've indicated that I need somebody to verify changes in actual, real environments that receive real e-mail to verify that those PRs do indeed work and not cause their own bugs. I do not currently and certainly won't in even the remote future be able to find the time to do those verifications myself.

We did a review of the pull request made by @pfouque 
For now everything is ok, in the next few days we will try Office365

**Comment by Pietro395** [comment]
@modernNeo 4.9.0 has been released

**Comment by ptav** [comment]
Hi both, I've reviewed the Django 4 pull request from @fluer. We're using that in production having merged with master. I'm also using o365 and all seems well for a few days now

**Comment by modernNeo** [comment]
> @modernNeo 4.9.0 has been released

@Pietro395 🥳 

But I would like to inquire if this means that a new release workflow has been established since @coddingtonbear has admitted they don't have time for maintenance?

**Comment by Pietro395** [comment]
> > @modernNeo 4.9.0 has been released
> 
> @Pietro395 🥳
> 
> But I would like to inquire if this means that a new release workflow has been established since @coddingtonbear has admitted they don't have time for maintenance?

:smiley:

It's still to be determined, in the meantime I'll try to help @coddingtonbear
