### ISSUE TITLE
Potential security issue

### ISSUE THREAD

**Issue by eranrund** [coddingtonbear/django-mailbox#42]
Hello,

There is a potential security issue with django_mailbox's admin. The Message admin displays HTML that is unsanitized and could potentially contain script tags. The following scenario, while slightly far fetched, is still a risk:
1) An attacker knows a certain address is fetched using django_mailbox
2) Attacker sends an email to that address containing javascript code that steals the user's cookie
3) Attacker waits and hopes the admin views his message

https://github.com/jsocol/bleach can be used to process the message's HTML before displaying it.

**Comment by coddingtonbear** [comment]
Hey there @eranrund -- I'm fairly sure that we don't as much display the HTML as we do output it to the template, and given that Django is kind enough to automatically escape any rendered strings (as long as they're not marked `|safe`), our rendering of an e-mail message's HTML content results in things like this (from a test e-mail I sent for another project the other day):

https://www.dropbox.com/s/dwse6lpwgrlan91/Screenshot%202015-03-07%2018.35.44.png?dl=0

Are you imagining a different avenue of attack that I'm overlooking?

**Comment by eranrund** [comment]
I am seeing a different picture (running with Django 1.7.5):
![image](https://cloud.githubusercontent.com/assets/1485066/6544327/5001df74-c4ff-11e4-9188-2a863f99c77f.png)

This is indeed weird - as I looked and I can't find any place that marks it safe, yet the links get displayed there...

**Comment by eranrund** [comment]
Update: After further digging into Django's admin code, I suspect this is a bug. The following code snippet renders fields (from env/lib/python2.7/site-packages/django/contrib/admin/helpers.py line 192):
```
                    result_repr = smart_text(value)
                    if getattr(attr, "allow_tags", False):
                        result_repr = mark_safe(result_repr)
                    else:
                        result_repr = linebreaksbr(result_repr)
```

linebreaksbr, unfortunately, behaves incorrectly:
```
In [2]: linebreaksbr('<a>test</a>')
Out[2]: u'<a>test</a>'

In [3]: type(_)
Out[3]: django.utils.safestring.SafeText
```

I will open a bug report with them and update :)

**Comment by coddingtonbear** [comment]
Awesome!  Thanks for posting that bug report to Django.

Cheers!

**Comment by eranrund** [comment]
Sure thing! Sorry for blaming django_mailbox without taking the time to actually look :)
They just released a new version today with the bugfix! I am impressed by how fast they moved, very cool of them.

**Comment by coddingtonbear** [comment]
No worries, @eranrund; honestly, you should probably continue to expect any found bugs being in my work rather than Django itself ;-).
