### ISSUE TITLE
imap folders

### ISSUE THREAD

**Issue by dmippoltiov** [coddingtonbear/django-mailbox#43]
Hi!
At this time i suppose there is no way to fetch mail from imap folders (other than Inbox) f.eg from
imap://user:pass@imap.server.tld/Selected
Do you have any plans to add such functionality in django-mailbox?

**Comment by coddingtonbear** [comment]
Nope, but pull requests are welcome.  If you add such a feature, feel free to send me a pull request, and I'll look into helping you merge that feature in.
