### ISSUE TITLE
No docs for model

### ISSUE THREAD

**Issue by ad-m** [coddingtonbear/django-mailbox#47]
I am want mark there is no docs for models. 

This make painful to use. Models class have very many (useful) methods, but I have to always analyse code to get knows how to use it.

Unfortunately, my English are not enough to write docs.

**Comment by ad-m** [comment]
Build failed: https://readthedocs.org/builds/django-mailbox/2604087/

**Comment by coddingtonbear** [comment]
Yup; see #50.

**Comment by ad-m** [comment]
Maybe https://github.com/rtfd/readthedocs.org/blob/master/docs/conf.py will be usefull.
