### ISSUE TITLE
TypeError at /backend/django_mailbox/mailbox/: 'str' does not support the buffer interface

### ISSUE THREAD

**Issue by synotna** [coddingtonbear/django-mailbox#49]
I'm assuming django-mailbox supports py3?

My first attempt getting mails, over IMAP

File "django_mailbox/transports/imap.py", line 50, in _get_all_message_ids
    return message_id_string.split(' ')

message_id_string =  b'3'

**Comment by synotna** [comment]
(python 3.4.3 & django 1.7.7)

**Comment by synotna** [comment]
Hm, imaplib returns bytestrings, did that behaviour change in 3.4?

**Comment by synotna** [comment]
' ' in split(' ') is unnecessary; simply split() works fine for spaces

>>> typ, data = server.search(None, 'ALL')
>>> data[0].split()
[b'1', b'2']

I'll test further tomorrow, not sure what else will break with the bytestrings :)

**Comment by synotna** [comment]
behaviour is the same in 3.3 which is passing tests, will continue looking tomorrow

**Comment by coddingtonbear** [comment]
You've *probably* found a bug; although django-mailbox nominally supports Python 3, I use it only on Python 2.7, so it's very possible for things to be overlooked.

Feel free to post a pull request patching things up if you feel really motivated, but I'll try to have a look over the next few days (and maybe consider wiring up some integration tests).

**Comment by coddingtonbear** [comment]
Thanks for reporting this, @synotna!  Although there are tests in place covering the IMAP transport, they were only unit tests, and (incorrectly) mocked-out the responses from the IMAP server.  I've fixed the unit test bug now, and added real integration tests around the IMAP functionality so this sort of thing can't happen again in the future.

Cheers!

**Comment by synotna** [comment]
Works great, thanks!
