### ISSUE TITLE
Message attachments are not always saved to disk

### ISSUE THREAD

**Issue by baster33** [coddingtonbear/django-mailbox#52]
Hello,

Is it possible to save '.txt' attachments in a file, the same way as other attachments?
I tried to set DJANGO_MAILBOX_TEXT_STORED_MIMETYPES to 'text/html', but it makes also an attachment without filename from message body, and it is not what i want. Maybe i'am missing something?

Best regards,
baster33

**Comment by Asitrax** [comment]
I'm facing the exact same problem.
I think the solution could be to change line 279 of django_mailbox/models.py 
from 
`elif msg.get_content_type() not in TEXT_STORED_MIMETYPES:`
to
`elif msg.get_content_type() not in TEXT_STORED_MIMETYPES or msg.get_filename():`
Or checking if `Content-Disposition: attachment;`

Example of attachments not being parsed when sent from Apple Mail:
`--Apple-Mail=_87FFBD75-9D11-48A8-B5C5-0EDEA646ABD3
Content-Disposition: attachment;
	filename=lorem_ipsum.txt
Content-Type: text/plain;
	name="lorem_ipsum.txt"
Content-Transfer-Encoding: quoted-printable`

and from Gmail:
`--94eb2c059d62f45f9d0519e60913
Content-Type: text/plain; charset=US-ASCII; name="lorem_ipsum.txt"
Content-Disposition: attachment; filename="lorem_ipsum.txt"
Content-Transfer-Encoding: base64
X-Attachment-Id: f_ibmcf3hr0`

Hope this helps!

**Comment by coddingtonbear** [comment]
Thanks for the heads-up on this one, @baster33 & @asitrax!  I've released a fix for this as part of v4.4.  Cheers!
