### ISSUE TITLE
Re-send incoming email

### ISSUE THREAD

**Issue by Edke** [coddingtonbear/django-mailbox#54]
Is there an easy way to re-send received django_mailbox.models.Message or easily create django.core.mail.messageEmailMessage from your Message model ?

**Comment by coddingtonbear** [comment]
I'm not sure I follow, do you mean to forward an e-mail message using this library?  If so, I'm afraid that that sort of functionality isn't something that a library like this one helps you with -- you'll still have to create your own `django.core.mail.message.EmailMessage` objects for sending using Django's built-in tools.

Am I understanding your question correctly?

**Comment by Edke** [comment]
Yes, right. I looked for easy way to create EmailMessage object from
incoming message, modify (change from, to) and send().

**Comment by coddingtonbear** [comment]
Nope!  Nothing like that.  That being said, building-up e-mail objects using `django.core.mail.message.EmailMessage` is super easy, so I wouldn't expect hand-writing forwarding logic to be too complicated in your own application code.  Keep in mind that you can always fetch the native python e-mail object, too, using the `get_email_object` method.  Good luck!
