### ISSUE TITLE
Incorrect bytestring decoding error handler 'REPLACE' (should be 'replace')

### ISSUE THREAD

**Issue by antcorro** [coddingtonbear/django-mailbox#55]
Hello.

I think there is an error in util.convert_header_to_unicode function at line 25:
    *return value.decode(encoding, 'REPLACE')*

this raise  LookupError: unknown error handler name 'REPLACE'

Replace should be in lowercase.
     *return value.decode(encoding, 'replace')*

Do you agree?

**Comment by coddingtonbear** [comment]
Oh my; I can't believe I didn't notice that before.  That's totally a bug; thanks for letting me know!  I'll try to have a glance at this today, but if you get to it earlier, feel free to post a pull request!

Cheers!
