### ISSUE TITLE
Missing migration

### ISSUE THREAD

**Issue by leifurhauks** [coddingtonbear/django-mailbox#56]
The migrations are not up to date with the models. After installing django_mailbox in my project, the next time I ran makemigrations the following migration was generated for django_mailbox:

	# -*- coding: utf-8 -*-
	from __future__ import unicode_literals

	from django.db import models, migrations

	class Migration(migrations.Migration):

	    dependencies = [
		('django_mailbox', '0003_auto_20150409_0316'),
	    ]

	    operations = [
		migrations.AlterField(
		    model_name='message',
		    name='eml',
		    field=models.FileField(help_text='Original full content of message', null=True, upload_to='messages', verbose_name='Raw message contents'),
		),
		migrations.AlterField(
		    model_name='messageattachment',
		    name='document',
		    field=models.FileField(verbose_name='Document', upload_to='mailbox_attachments/%Y/%m/%d/'),
		),
	    ]

**Comment by willhcr** [comment]
I've seen this issue as well. From what I can see it is because the migration file is using byte strings instead of regular strings which Django migrations detects as being different.

```python
field=models.FileField(help_text='Original full content of message', upload_to=b'messages', null=True, verbose_name='Message as a file'),
('document', models.FileField(upload_to=b'mailbox_attachments/%Y/%m/%d/', verbose_name='Document')),
```

**Comment by antcorro** [comment]
Hi.
Which version of django and django_mailbox do you use?
I'm working with django 1.7.7 and django_mailbox 4.4.1 and the migrations are ok. I not able to reproduce the issue

**Comment by leifurhauks** [comment]
I'm using django 1.8.3 and django_mailbox 4.4.1 with python 3.4.3. I also just produced the same result in django 1.7.7 (again with py3). Both in virtualenvs. If @willhcr 's suggestion above about bytestrings is correct, maybe this only affects python3?

**Comment by coddingtonbear** [comment]
Yes, I agree, it's more than likely related to the byte strings thing and thus Python 3 only. I'll try to find a little time to look into this this week, but if one of you happens to have a branch already, i can promise a quick review and merge :-).

Thanks for noticing this!

**Comment by coddingtonbear** [comment]
Just released the fix!  Thanks for posting the PR @willhcr!

**Comment by willhcr** [comment]
Thanks!
