### ISSUE TITLE
Setting a script with incoming mail

### ISSUE THREAD

**Issue by ArandirTA** [coddingtonbear/django-mailbox#60]
Hello everyone,
I would like to run a script for each incoming mail, like this:
run_script(email) 

How is it possible ?

**Comment by ad-m** [comment]
Use signals. See
https://github.com/watchdogpolska/poradnia/blob/master/poradnia/letters/models.py

Wysłano z urządzenia mobilnego.
28 lip 2015 20:53 "ArandirTA" <notifications@github.com> napisał(a):

Hello everyone,
I would like to run a script for each incoming mail, like this:
run_script(email)

How is it possible ?

—
Reply to this email directly or view it on GitHub
<https://github.com/coddingtonbear/django-mailbox/issues/60>.

**Comment by ArandirTA** [comment]
It works. Thanks

**Comment by ad-m** [comment]
It is documented http://django-mailbox.readthedocs.org/en/latest/topics/signal.html . You don't have to copy data from messages. Messages are stored. I do it in result of pre-computing and performance issues.

**Comment by coddingtonbear** [comment]
![](http://media.giphy.com/media/10Y2YMUNmQa9a0/giphy.gif)
