### ISSUE TITLE
Q. How to test incoming messages ?

### ISSUE THREAD

**Issue by harmo** [coddingtonbear/django-mailbox#68]
Hello, 
I'm trying to test the *message* part of my application.

I can create Mailboxes and link it to my test users, but how to simulate new incoming messages ?
I have to fill **ALL** the Message objects and save it or there is a simply way ?

Thanks in advance !

**Comment by ad-m** [comment]
Hello,

You can create fixtures and use them. See django-mailbox tests fg. https://github.com/coddingtonbear/django-mailbox/blob/master/django_mailbox/tests/test_process_email.py#L17 .

Greetings,

**Comment by harmo** [comment]
Yep I finally did with those templates, thank you !
