### ISSUE TITLE
How to replay email as mailbox owner?

### ISSUE THREAD

**Issue by gusreyes01** [coddingtonbear/django-mailbox#69]
I'd like to compose a new email but not being sent by the email setup in my server., but as the owner of the mailbox. Can this be done through POP3?

**Comment by coddingtonbear** [comment]
Unfortunately, you cannot use POP3 for _sending_ e-mail messages, but you can use SMTP.  If you haven't came across [the reply method](https://github.com/coddingtonbear/django-mailbox/blob/master/django_mailbox/models.py#L547), you may want to start there, and it *should* set the "From" field of the message to match the mailbox' e-mail address automatically.

Feel free to reply here if that didn't answer your question, or hop into the [gitter channel for this project](https://gitter.im/coddingtonbear/django-mailbox) if you need one-on-one help.

Cheers!

**Comment by gusreyes01** [comment]
I ended up starting a new connection for each signed user, something like this:

		# Email sender settings
		my_host = 'secure.emailsrvr.com'
		my_port = 465
		my_username = 'test@karen-huber.com'
		my_password = 'xxxxx!'
		my_use_tls = False
		my_use_ssl = True
		connection = get_connection(host=my_host,
									port=my_port,
									username=my_username,
									password=my_password,
									use_tls=my_use_tls,
									use_ssl=my_use_ssl)

However I'll dig a little more into the reply method to see if it's what I need.

Thanks for the quick response!
