### ISSUE TITLE
Folder and Archive options not working for python<2.7.4

### ISSUE THREAD

**Issue by pkaczynski** [coddingtonbear/django-mailbox#71]
There is a "feature" in python<2.7.4 and urlparse that parses query string to path portion if scheme is uknown (and imap+ssl is an unknown scheme).

This makes archive and folder options unusable on older installations, like ubuntu 12.04 (with python 2.7.3)

**Comment by coddingtonbear** [comment]
Ahh; that might be the case.  Unfortunately, I'm under the impression that version of Python that old are fairly infrequent these days (and less frequent every day) so I'm not sure I see fixing that bug as a necessity.  That said, if you'd like to contribute a patch, feel free @pkaczynski!

Cheers!
