### ISSUE TITLE
No received date/time field?

### ISSUE THREAD

**Issue by rulzart** [coddingtonbear/django-mailbox#73]
Hi

I first noticed your addon a couple of years ago, and I am finaly back to implement it on my site :)

But there doesn't seem to be a "received date/time" field in the Message model, and no property to get it either.

And how does it handle Cc and Bcc?

**Comment by coddingtonbear** [comment]
There is both a `processed` field, and you can access any headers (including `cc`) on the [original message object](https://docs.python.org/2/library/email.message.html) using the `get_email_object` method.

Good luck, @rulzart!

**Comment by rulzart** [comment]
Hi coddington

Yes, there is a processed field, but that is the date/time the emails have been processed by the addon. This might be ok for future emails, but old emails will all have the same processed date (the date you first run the getmail function). I will try to write some code to solve this problem. Maybe the best solution is to make a proxy model.

Regards

**Comment by coddingtonbear** [comment]
Yup!  You could do that -- but you could also use the headers on the actual e-mail object for getting the send date using the message object I described above, too.

**Comment by rulzart** [comment]
Yes, I get that. But then I will need to convert it from str to datetime if I want to format it in a special way.

Just saying, that having a received date field might be a good idea - it makes it easier to sort by, and easier to format the output (like %dd-%MM-%YY).
