### ISSUE TITLE
Update to support pluggable User models

### ISSUE THREAD

**Issue by coddingtonbear** [coddingtonbear/django-mailbox#75]
This shouldn't be too big of a deal, really, and it's far, far overdue.

**Comment by ad-m** [comment]
Where do you have any hard reference to User mdels? I don't see any https://github.com/coddingtonbear/django-mailbox/search?utf8=%E2%9C%93&q=User . 

I use swappable models, so I can fix that, but I don't see this issue.

**Comment by coddingtonbear** [comment]
Ooo -- you're right, @ad-m.  Honestly, I was just looking for an easy way to get a green commit marker on my profile for today by opening this issue, and had genuinely thought that I had a `ForeignKey` to `django.contrib.auth.models.User`. You're right, though; there isn't one.

Thanks for the heads up!

**Comment by eriktelepovsky** [comment]
Hi. I don't see any user foreign field reference in the Mailbox model. What is the best way to connect user model with mailboxes?

**Comment by eriktelepovsky** [comment]
Created pull request #155
