### ISSUE TITLE
How to download attachments from admin panel?

### ISSUE THREAD

**Issue by cheremovsky** [coddingtonbear/django-mailbox#77]
I got the attachment downloaded in mailbox_attachments folder in project root directory, but all the attachment links of kind     `http://127.0.0.1:8000/admin/django_mailbox/message/349/mailbox_attachments/2016/01/10/file.pdf/` are unavailable with error 
`message object with primary key 'path_to_file' does not exist.` 
raised by `django.contrib.admin.options.change_view`

How to fix it?

**Comment by coddingtonbear** [comment]
I'm afraid I'm not able to reproduce such a problem, @cheremovsky; it *sounds* like maybe you don't have your `MEDIA_URL` set properly; could that be true?

Check out this documentation if you need a tip: https://docs.djangoproject.com/en/1.9/ref/settings/#std:setting-MEDIA_URL
