### ISSUE TITLE
GMAIL OAuth2 gives AUTHENTICATIONFAILED

### ISSUE THREAD

**Issue by pa-jama** [coddingtonbear/django-mailbox#80]
Hello,

I am using python-social-auth.
Its working well and I can login to my site using google.

However, when I follow the docs, and use like this
gmail+ssl://youremailaddress%40yourdomain.com.com:oauth2@imap.gmail.com?archive=Archived
It always gives authentication failed, presumably because the oauth2 password fails.
But why does it even need to use the password? It should be able to grab the auth token from python social auth.

The docs could be missing something?
but in the code, get_connection method seems to always try to use a password

**Comment by coddingtonbear** [comment]
As [mentioned in the docs](http://django-mailbox.readthedocs.org/en/latest/topics/mailbox_types.html#gmail-imap-with-oauth2-authentication), the password is used if no connection could be established with OAuth (see https://github.com/coddingtonbear/django-mailbox/blob/master/django_mailbox/transports/gmail.py#L11 for details).  Given the description you've posted above, It *sounds* like OAuth is failing for you.  Are you sure you've stored your credentials properly with `python-social-auth`?

**Comment by pa-jama** [comment]
You're right, OAuth is failing. I just can't see why
I've tried debugging but all I get is that short error below, which doesn't tell me much.
     
    > /srv/env/techday/lib/python2.7/site-packages/django_mailbox/transports/gmail.py(57)_connect_oauth()
     -> self.server.authenticate('XOAUTH2', lambda x: auth_string)
    (Pdb) n
    n
    error: error('[...ilure)',)
    > /srv/env/techday/lib/python2.7/site-packages/django_mailbox/transports/gmail.py(57)_connect_oauth()
    -> self.server.authenticate('XOAUTH2', lambda x: auth_string)

**Comment by pa-jama** [comment]
It was hard to find out why as the error was buried, so I had to deconstruct.
Anyways, configuration issue as I didn't realise it had to be "Other" rather than "Web Application"

> The redirect URI in the request: urn:ietf:wg:oauth:2.0:oob can only be used by a Client ID for native application. It is not allowed for the &#39;WEB&#39; client type. You can create a Client ID for native application in the Credentials section of the Google Developers Console.

**Comment by coddingtonbear** [comment]
Awesome, @pa-jama -- I'm glad you found the answer!

**Comment by arun10797** [comment]
I am authenticated with django_social, But i am not able to retrieve the mails from gmail.
I am getting following error.
![screenshot from 2018-08-21 16-26-15](https://user-images.githubusercontent.com/21377608/44397718-fa523300-a55e-11e8-88f6-6aaffe2d3105.png)

**Comment by coddingtonbear** [comment]
I think you might find the answer you're looking for by going to the link the error message is directing you to, @arun10797.

**Comment by calcgendev** [comment]
Error while using oauth2 to get gmail mails. But could successfully obtain using the email and password.
![image](https://user-images.githubusercontent.com/46434303/111110768-3fa73780-8585-11eb-977d-41d68e95f49e.png)

Generated oauth credential using web
![image](https://user-images.githubusercontent.com/46434303/111110833-5b124280-8585-11eb-9965-1b847298d431.png)

**Comment by Grunze1s** [comment]
Error on fetch email from gmail using oauth2 but could be fetched using email and password

![image](https://user-images.githubusercontent.com/31089458/111111274-29e64200-8586-11eb-9dc0-6f9ae0b2f7ce.png)

oauth2 credentials is generated using web because only option available options are

![image](https://user-images.githubusercontent.com/31089458/111111163-f86d7680-8585-11eb-82ed-4eb9e73b5e00.png)
