### ISSUE TITLE
Attachments sometimes are being saved as *.bin instead of the actual filetypes.

### ISSUE THREAD

**Issue by cheremovsky** [coddingtonbear/django-mailbox#96]
The title is pretty much self-explained.
Files itself are OK. If I manually rename some *.bin to the actual attachment's filetype it can be opened alright.

**Comment by ad-m** [comment]
Do you can save broken eml file and provide it here?

**Comment by cheremovsky** [comment]
Sure, here's an eml with attachments.
https://drive.google.com/file/d/0B1vmuaQXbRM8NVkwUm9jNFh4Wnc/view?usp=sharing
4.1MB

**Comment by coddingtonbear** [comment]
Glancing at the e-mail, it looks like the attachment filenames are (properly) encoded in koi-8r; I wonder if the [filename we're given when we call .get_filename()](https://github.com/coddingtonbear/django-mailbox/blob/master/django_mailbox/models.py#L302) isn't decoding that into a unicode.  @ad-m; I can do a little digging on this if you haven't already started; let me know if you have!

**Comment by cheremovsky** [comment]
Hi guys! Sorry for disturbing, any news so far?

**Comment by ad-m** [comment]
I don't do anything.

Wysłano z urządzenia mobilnego.
11 maj 2016 14:14 "cheremovsky" <notifications@github.com> napisał(a):

**Comment by coddingtonbear** [comment]
Fixed as part of 4.4.9; thanks for the heads-up about this, @cheremovsky!
